### ISSUE TITLE
8.0 PHP Deprecated Notices

### ISSUE THREAD

**Issue by dimensionmedia** [LionSher-Technologies/soliloquy-lite#26]
Tested with WordPress 5.2 Beta

- PHP Deprecated:  Required parameter $post follows optional parameter $type in /Users/dimensionmedia/Sites/enviralatest.test/public_html/wp-content/plugins/soliloquy-lite/includes/admin/metaboxes.php on line 660

**Comment by chrisakelley** [comment]
fixed in 2.7.1
