### ISSUE TITLE
Fix Missing Menu Tab Icons

### ISSUE THREAD

**Issue by dimensionmedia** [LionSher-Technologies/soliloquy-lite#27]
![Screen Shot 2021-12-13 at 3 53 26 PM](https://user-images.githubusercontent.com/721134/145887146-f6229910-d351-4e94-8d09-dad418eeb9e7.png)

**Comment by bmilligan15** [comment]
Looking good on my end.

![image](https://user-images.githubusercontent.com/17555874/146034685-48c27172-2033-4f77-beff-fd7a77ee12d7.png)

Thank you!

**Comment by greatknave** [comment]
This looks good on my local, as well.
