### ISSUE TITLE
PHP notice w/PHP 8: Undefined array key "action"

### ISSUE THREAD

**Issue by bmilligan15** [LionSher-Technologies/soliloquy-lite#33]
Report came in on .org, and I'm able to replicate locally. https://wordpress.org/support/topic/bug-in-includes-admin-editor-php-line-104/#post-15897777

<img width="887" alt="image" src="https://user-images.githubusercontent.com/17555874/183436747-0d562d8c-dcce-4db3-9d7a-02f801f29aca.png">

Notice doesn't appear when running PHP 7.3 or 7.4.

**Comment by chrisakelley** [comment]
fixed in 2.7.1
